In [ ]:
import pandas as pd

In [1]:
!mkdir temp_data

In [1]:
# here I'm loading my old block-precinct data recovered from Google Fusion Tables
!curl "https://s3.amazonaws.com/media.johnkeefe.net/nypd-data/NYC_Blocks_2010CensusData_plus_NYPD_precincts.csv" -o data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.1M  100 14.1M    0     0  14.4M      0 --:--:-- --:--:-- --:--:-- 14.4M

In [7]:
!mv data.csv ./temp_data

In [17]:
df = pd.read_csv("./temp_data/data.csv")

In [18]:
df.head()

,geoid10,precinct,SUMLEV,STATE,COUNTY,TRACT,BLOCK,INTPTLAT,INTPTLON,P0010001,...,geometry,geometry_vertex_count,SHAPE_Leng,SHAPE_Area,import_notes,Precinct,SHAPE_Leng.1,SHAPE_Area.1,import_notes.1,precinct.1
0,360050001000001,NaN,750,36,5,100,1,40.793109,-73.869659,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,360050001000002,NaN,750,36,5,100,2,40.798113,-73.892358,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,360050001001000,114.0,750,36,5,100,1000,40.794386,-73.880803,8634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.0
3,360050001001001,114.0,750,36,5,100,1001,40.797144,-73.887119,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.0
4,360050001001002,114.0,750,36,5,100,1002,40.792209,-73.882048,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.0

In [33]:
df['Precinct'].value_counts()

Series([], Name: Precinct, dtype: int64)

In [38]:
df.columns

Index(['geoid10', 'precinct', 'SUMLEV', 'STATE', 'COUNTY', 'TRACT', 'BLOCK',
       'INTPTLAT', 'INTPTLON', 'P0010001',
       ...
       'geometry', 'geometry_vertex_count', 'SHAPE_Leng', 'SHAPE_Area',
       'import_notes', 'Precinct', 'SHAPE_Leng.1', 'SHAPE_Area.1',
       'import_notes.1', 'precinct.1'],
      dtype='object', length=163)

In [39]:
list(df.columns)

['geoid10',
 'precinct',
 'SUMLEV',
 'STATE',
 'COUNTY',
 'TRACT',
 'BLOCK',
 'INTPTLAT',
 'INTPTLON',
 'P0010001',
 'P0010002',
 'P0010003',
 'P0010004',
 'P0010005',
 'P0010006',
 'P0010007',
 'P0010008',
 'P0010009',
 'P0010010',
 'P0010011',
 'P0010012',
 'P0010013',
 'P0010014',
 'P0010015',
 'P0010016',
 'P0010017',
 'P0010018',
 'P0010019',
 'P0010020',
 'P0010021',
 'P0010022',
 'P0010023',
 'P0010024',
 'P0010025',
 'P0010026',
 'P0010027',
 'P0010028',
 'P0010029',
 'P0010030',
 'P0010031',
 'P0010032',
 'P0010033',
 'P0010034',
 'P0010035',
 'P0010036',
 'P0010037',
 'P0010038',
 'P0010039',
 'P0010040',
 'P0010041',
 'P0010042',
 'P0010043',
 'P0010044',
 'P0010045',
 'P0010046',
 'P0010047',
 'P0010048',
 'P0010049',
 'P0010050',
 'P0010051',
 'P0010052',
 'P0010053',
 'P0010054',
 'P0010055',
 'P0010056',
 'P0010057',
 'P0010058',
 'P0010059',
 'P0010060',
 'P0010061',
 'P0010062',
 'P0010063',
 'P0010064',
 'P0010065',
 'P0010066',
 'P0010067',
 'P0010068',
 'P0010069',
 'P0010070',
 'P0010071',
 'P0020001',
 'P0020002',
 'P0020003',
 'P0020004',
 'P0020005',
 'P0020006',
 'P0020007',
 'P0020008',
 'P0020009',
 'P0020010',
 'P0020011',
 'P0020012',
 'P0020013',
 'P0020014',
 'P0020015',
 'P0020016',
 'P0020017',
 'P0020018',
 'P0020019',
 'P0020020',
 'P0020021',
 'P0020022',
 'P0020023',
 'P0020024',
 'P0020025',
 'P0020026',
 'P0020027',
 'P0020028',
 'P0020029',
 'P0020030',
 'P0020031',
 'P0020032',
 'P0020033',
 'P0020034',
 'P0020035',
 'P0020036',
 'P0020037',
 'P0020038',
 'P0020039',
 'P0020040',
 'P0020041',
 'P0020042',
 'P0020043',
 'P0020044',
 'P0020045',
 'P0020046',
 'P0020047',
 'P0020048',
 'P0020049',
 'P0020050',
 'P0020051',
 'P0020052',
 'P0020053',
 'P0020054',
 'P0020055',
 'P0020056',
 'P0020057',
 'P0020058',
 'P0020059',
 'P0020060',
 'P0020061',
 'P0020062',
 'P0020063',
 'P0020064',
 'P0020065',
 'P0020066',
 'P0020067',
 'P0020068',
 'P0020069',
 'P0020070',
 'P0020071',
 'P0020072',
 'P0020073',
 'geometry',
 'geometry_vertex_count',
 'SHAPE_Leng',
 'SHAPE_Area',
 'import_notes',
 'Precinct',
 'SHAPE_Leng.1',
 'SHAPE_Area.1',
 'import_notes.1',
 'precinct.1']

Need to get rid of some of the extra columns Fusion tables had added.

In [42]:
df.drop(columns=['geometry',
 'geometry_vertex_count',
 'SHAPE_Leng',
 'SHAPE_Area',
 'import_notes',
 'Precinct',
 'SHAPE_Leng.1',
 'SHAPE_Area.1',
 'import_notes.1',
 'precinct.1'], inplace=True)

In [43]:
df

,geoid10,precinct,SUMLEV,STATE,COUNTY,TRACT,BLOCK,INTPTLAT,INTPTLON,P0010001,...,P0020064,P0020065,P0020066,P0020067,P0020068,P0020069,P0020070,P0020071,P0020072,P0020073
0,360050001000001,NaN,750,36,5,100,1,40.793109,-73.869659,0,...,0,0,0,0,0,0,0,0,0,0
1,360050001000002,NaN,750,36,5,100,2,40.798113,-73.892358,0,...,0,0,0,0,0,0,0,0,0,0
2,360050001001000,114.0,750,36,5,100,1000,40.794386,-73.880803,8634,...,0,0,0,0,0,0,0,0,0,0
3,360050001001001,114.0,750,36,5,100,1001,40.797144,-73.887119,0,...,0,0,0,0,0,0,0,0,0,0
4,360050001001002,114.0,750,36,5,100,1002,40.792209,-73.882048,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39143,360859901000009,NaN,750,36,85,990100,9,40.495132,-74.184591,0,...,0,0,0,0,0,0,0,0,0,0
39144,360859901000010,NaN,750,36,85,990100,10,40.489006,-74.210906,0,...,0,0,0,0,0,0,0,0,0,0
39145,360859901000011,NaN,750,36,85,990100,11,40.486407,-74.227048,0,...,0,0,0,0,0,0,0,0,0,0
39146,360859901000012,NaN,750,36,85,990100,12,40.488618,-74.243632,0,...,0,0,0,0,0,0,0,0,0,0
39147,360859901000013,NaN,750,36,85,990100,13,40.496200,-74.257313,0,...,0,0,0,0,0,0,0,0,0,0

Here I rebuild the "Rosetta Stone" csv. I originally did this with QGIS many years ago.

In [46]:
df2 = pd.DataFrame()

In [47]:
df2['geoid10'] = df['geoid10']

In [ ]:
df2['precinct'] = df['precinct'].astype('Int64')  ## note that capital I in Int64, which allows for nulls

In [54]:
df2

               geoid10  precinct
0      360050001000001      <NA>
1      360050001000002      <NA>
2      360050001001000       114
3      360050001001001       114
4      360050001001002       114
...                ...       ...
39143  360859901000009      <NA>
39144  360859901000010      <NA>
39145  360859901000011      <NA>
39146  360859901000012      <NA>
39147  360859901000013      <NA>

[39148 rows x 2 columns]

In [56]:
df2.to_csv("./temp_data/rosetta.csv", index=False)

In [58]:
df.to_csv("./temp_data/nyc_census2020blocks_with_police_precincts.csv", index = False)

## Updating for 2020 police precinct boundaries

In [234]:
df_main = pd.read_csv("./temp_data/rosetta.csv")
# df_main = pd.read_csv("./temp_data/precinct_block_key.csv")

In [183]:
df_main

               geoid10  precinct
0      360050001000001       NaN
1      360050001000002       NaN
2      360050001001000     114.0
3      360050001001001     114.0
4      360050001001002     114.0
...                ...       ...
39143  360859901000009       NaN
39144  360859901000010       NaN
39145  360859901000011       NaN
39146  360859901000012       NaN
39147  360859901000013       NaN

[39148 rows x 2 columns]

In [184]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39148 entries, 0 to 39147
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   geoid10   39148 non-null  int64
 1   precinct  38610 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 611.8 KB

Set up a little function add a new "reset" column ... which will clear out all the staten island precincts
but leave the rest.

In [185]:
import numpy as np
def reset_calc(row):
    if row['precinct'] >= 120:
        val = np.nan
    else:
        val = row['precinct']
    return val

In [186]:
df_main['reset'] =  df_main.apply(reset_calc, axis=1)

In [187]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39148 entries, 0 to 39147
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   geoid10   39148 non-null  int64
 1   precinct  38610 non-null  float64
 2   reset     33616 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 917.7 KB

### Fixing Staten Island

Since I originally did this work, Staten Island added another police precinct â€” dividing the island into four zones instead of three. In QGIS, I reworked that area, exporting block lists for each precinct. Here I read those in and then update the existing list with the new precincts.

In [ ]:
df_120= pd.read_csv('../data/nyc/all_blocks_in_120.csv')
df_120['new_precinct'] = 120

In [ ]:
df_121= pd.read_csv('../data/nyc/all_blocks_in_121.csv')
df_121['new_precinct'] = 121

In [ ]:
df_122= pd.read_csv('../data/nyc/all_blocks_in_122.csv')
df_122['new_precinct'] = 122

In [37]:
df_123= pd.read_csv('../data/nyc/all_blocks_in_123.csv')

In [38]:
df_123['new_precinct'] = 123

In [39]:
df_123

,STATEFP10,COUNTYFP10,TRACTCE10,BLOCKCE10,GEOID10,NAME10,MTFCC10,UR10,UACE10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,LONGITUDE,LATITUDE,new_precinct
0,36,85,17600,3037,360850176003037,Block 3037,G5040,NaN,NaN,S,10769,0,40.522619,-74.175455,-74.175455,40.522619,123
1,36,85,20803,2017,360850208032017,Block 2017,G5040,NaN,NaN,S,9511,0,40.535913,-74.208958,-74.208958,40.535913,123
2,36,85,24402,1021,360850244021021,Block 1021,G5040,NaN,NaN,S,1823,0,40.503652,-74.238563,-74.238563,40.503652,123
3,36,85,17012,3004,360850170123004,Block 3004,G5040,NaN,NaN,S,16219,0,40.551326,-74.176246,-74.176246,40.551326,123
4,36,85,17012,1001,360850170121001,Block 1001,G5040,NaN,NaN,S,7650,0,40.558354,-74.172080,-74.172080,40.558354,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1213,36,85,17012,3003,360850170123003,Block 3003,G5040,NaN,NaN,S,19205,0,40.552448,-74.176149,-74.176149,40.552448,123
1214,36,85,17008,3007,360850170083007,Block 3007,G5040,NaN,NaN,S,22563,0,40.552273,-74.183819,-74.183819,40.552273,123
1215,36,85,17012,1008,360850170121008,Block 1008,G5040,NaN,NaN,S,29191,0,40.556850,-74.170058,-74.170058,40.556850,123
1216,36,85,17012,2018,360850170122018,Block 2018,G5040,NaN,NaN,S,16663,0,40.550503,-74.170970,-74.170970,40.550503,123
1217,36,85,17012,2019,360850170122019,Block 2019,G5040,NaN,NaN,S,14619,0,40.550797,-74.168709,-74.168709,40.550796,123

Concatinate those.

In [50]:
df_statenisland = pd.concat([df_120, df_121, df_122, df_123], ignore_index=True)

In [188]:
df_statenisland

,STATEFP10,COUNTYFP10,TRACTCE10,BLOCKCE10,GEOID10,NAME10,MTFCC10,UR10,UACE10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,LONGITUDE,LATITUDE,new_precinct
0,36,85,4700,1020,360850047001020,Block 1020,G5040,NaN,NaN,S,17348,0,40.617243,-74.099298,-74.099298,40.617243,120
1,36,85,2100,2000,360850021002000,Block 2000,G5040,NaN,NaN,S,450424,0,40.632177,-74.071437,-74.071437,40.632177,120
2,36,85,16901,2017,360850169012017,Block 2017,G5040,NaN,NaN,S,12684,0,40.612337,-74.101805,-74.101805,40.612337,120
3,36,85,16901,2016,360850169012016,Block 2016,G5040,NaN,NaN,S,12361,0,40.612632,-74.100994,-74.100994,40.612632,120
4,36,85,16901,2025,360850169012025,Block 2025,G5040,NaN,NaN,S,1337,0,40.611035,-74.102814,-74.102814,40.611035,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5017,36,85,17012,3003,360850170123003,Block 3003,G5040,NaN,NaN,S,19205,0,40.552448,-74.176149,-74.176149,40.552448,123
5018,36,85,17008,3007,360850170083007,Block 3007,G5040,NaN,NaN,S,22563,0,40.552273,-74.183819,-74.183819,40.552273,123
5019,36,85,17012,1008,360850170121008,Block 1008,G5040,NaN,NaN,S,29191,0,40.556850,-74.170058,-74.170058,40.556850,123
5020,36,85,17012,2018,360850170122018,Block 2018,G5040,NaN,NaN,S,16663,0,40.550503,-74.170970,-74.170970,40.550503,123
5021,36,85,17012,2019,360850170122019,Block 2019,G5040,NaN,NaN,S,14619,0,40.550797,-74.168709,-74.168709,40.550796,123

In [189]:
df_statenisland.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5022 entries, 0 to 5021
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   STATEFP10     5022 non-null   int64
 1   COUNTYFP10    5022 non-null   int64
 2   TRACTCE10     5022 non-null   int64
 3   BLOCKCE10     5022 non-null   int64
 4   GEOID10       5022 non-null   int64
 5   NAME10        5022 non-null   object
 6   MTFCC10       5022 non-null   object
 7   UR10          0 non-null      float64
 8   UACE10        0 non-null      float64
 9   FUNCSTAT10    5022 non-null   object
 10  ALAND10       5022 non-null   int64
 11  AWATER10      5022 non-null   int64
 12  INTPTLAT10    5022 non-null   float64
 13  INTPTLON10    5022 non-null   float64
 14  LONGITUDE     5022 non-null   float64
 15  LATITUDE      5022 non-null   float64
 16  new_precinct  5022 non-null   int64
dtypes: float64(6), int64(8), object(3)
memory usage: 667.1+ KB

In [190]:
# Merge the new info into the old table, adding a "new_precinct" column in the process
merged = df_main.merge(df_statenisland, left_on="geoid10", right_on="GEOID10", how="left")

In [191]:
merged.to_csv('./temp_data/merged.csv')

In [192]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39151 entries, 0 to 39150
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geoid10       39151 non-null  int64
 1   precinct      38613 non-null  float64
 2   reset         33616 non-null  float64
 3   STATEFP10     5022 non-null   float64
 4   COUNTYFP10    5022 non-null   float64
 5   TRACTCE10     5022 non-null   float64
 6   BLOCKCE10     5022 non-null   float64
 7   GEOID10       5022 non-null   float64
 8   NAME10        5022 non-null   object
 9   MTFCC10       5022 non-null   object
 10  UR10          0 non-null      float64
 11  UACE10        0 non-null      float64
 12  FUNCSTAT10    5022 non-null   object
 13  ALAND10       5022 non-null   float64
 14  AWATER10      5022 non-null   float64
 15  INTPTLAT10    5022 non-null   float64
 16  INTPTLON10    5022 non-null   float64
 17  LONGITUDE     5022 non-null   float64
 18  LATITUDE      5022 non-null   float64
 19  new_precinct  5022 non-null   float64
dtypes: float64(16), int64(1), object(3)
memory usage: 6.3+ MB

### Other fixes

There were some other changes made in the last few years, including adjustments where three precicnts meet near the (relatively) new Barclays Center. These steps will change individual rows, by the block number, by adding values into the "new_precincts" column.

In [193]:
merged.loc[merged['geoid10'] == 360050397001000, ['new_precinct']] = 48

In [194]:
# let's see if that worked
merged.loc[merged['geoid10'] == 360050397001000]

,geoid10,precinct,reset,STATEFP10,COUNTYFP10,TRACTCE10,BLOCKCE10,GEOID10,NAME10,MTFCC10,UR10,UACE10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,LONGITUDE,LATITUDE,new_precinct
4572,360050397001000,52.0,52.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0

In [195]:
to_52 = [360610309001005,360610309001004]
for item in to_52:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 52

In [196]:
# let's see if that worked
merged.loc[merged['geoid10'] == 360610309001004]

,geoid10,precinct,reset,STATEFP10,COUNTYFP10,TRACTCE10,BLOCKCE10,GEOID10,NAME10,MTFCC10,UR10,UACE10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,LONGITUDE,LATITUDE,new_precinct
19140,360610309001004,50.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0

In [197]:
to_change = [360610265003001]
for item in to_change:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 34

In [198]:
to_change = [360810317001000,
360810317001001,
360810107010002,
360810331000007]
for item in to_change:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 114

In [199]:
to_change = [360810641021018,
360810641021021,
360810641021022,
360810641021015,
360810641021014,
360810641021013,
360810641021017,
360810639001000,
360810641021007,
360810641021002,
360810773001005,
360810641021003,
360810773001006,
360810773001004]
for item in to_change:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 102

In [200]:
to_change = [360810033001014,
360810019001000,
360810019001011,
360810019001017,
360810025006001,
360810033001010,
360810033001011,
360810033001012]
for item in to_change:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 108

In [201]:
to_change = [360470163002001,
360470163001002,
360470161003007,
360470129011000,
360470129011002,
360470161001002,
360470163001001,
360470163002000,
360470159001000,
360470163003000,
360470035001006,
360470161003005,
360470129011001,
360470161002000,
360470163001000,
360470161001001,
360470161002001,
360470163003001,
360470161001000,
360470035001007,
360470129021000]
for item in to_change:
    merged.loc[merged['geoid10'] == item, ['new_precinct']] = 78

In [202]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39151 entries, 0 to 39150
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geoid10       39151 non-null  int64
 1   precinct      38613 non-null  float64
 2   reset         33616 non-null  float64
 3   STATEFP10     5022 non-null   float64
 4   COUNTYFP10    5022 non-null   float64
 5   TRACTCE10     5022 non-null   float64
 6   BLOCKCE10     5022 non-null   float64
 7   GEOID10       5022 non-null   float64
 8   NAME10        5022 non-null   object
 9   MTFCC10       5022 non-null   object
 10  UR10          0 non-null      float64
 11  UACE10        0 non-null      float64
 12  FUNCSTAT10    5022 non-null   object
 13  ALAND10       5022 non-null   float64
 14  AWATER10      5022 non-null   float64
 15  INTPTLAT10    5022 non-null   float64
 16  INTPTLON10    5022 non-null   float64
 17  LONGITUDE     5022 non-null   float64
 18  LATITUDE      5022 non-null   float64
 19  new_precinct  5073 non-null   float64
dtypes: float64(16), int64(1), object(3)
memory usage: 6.3+ MB

This function will make the precinct_2020 column based on the old precint or, if there's
a new one, the new precinct.

In [203]:
def make_2020(row):
    if pd.isnull(row['new_precinct']):
        val = row['precinct']
    else:
        val = row['new_precinct']
    return val

In [204]:
merged['precinct_2020'] =  merged.apply(make_2020, axis=1)

In [205]:
merged.to_csv('./temp_data/merged2020.csv')

In [206]:
rosetta_2020_df = pd.DataFrame()
rosetta_2020_df['geoid10'] = merged['geoid10']

In [207]:
rosetta_2020_df['precinct_2020'] = merged['precinct_2020'].astype('Int64')

In [208]:
rosetta_2020_df.to_csv('./temp_data/precinct_block_key_2020.csv', index=False)

In [209]:
rosetta_2020_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39151 entries, 0 to 39150
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   geoid10        39151 non-null  int64
 1   precinct_2020  38639 non-null  Int64
dtypes: Int64(1), int64(1)
memory usage: 955.8 KB

Bring in all the census data for every block.

In [210]:
census_df = pd.read_csv('./temp_data/nyc_census2020blocks_with_police_precincts.csv')

In [211]:
census_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39148 entries, 0 to 39147
Columns: 153 entries, geoid10 to P0020073
dtypes: float64(3), int64(150)
memory usage: 45.7 MB

Hmmmm. we have three too many rows. What happened?

In [212]:
rosetta_2020_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
39146    False
39147    False
39148    False
39149    False
39150    False
Length: 39151, dtype: bool

In [213]:
rosetta_2020_df.duplicated(subset='geoid10', keep='first').sum()

3

Ah, there are three duplicate block numbers.

In [214]:
duplicateRowsDF = rosetta_2020_df[rosetta_2020_df.duplicated(['geoid10'], keep=False)]
 
print("Duplicate Rows based on a single column are:", duplicateRowsDF, sep='\n')

Duplicate Rows based on a single column are:
               geoid10  precinct_2020
37191  360850181001001            121
37192  360850181001001            122
37193  360850181001002            121
37194  360850181001002            122
37245  360850187011003            120
37246  360850187011003            121

looking at the map ... all are little slivers
```
360850181001001 is in 122
360850181001002 is in 122
360850187011003 is mostly in 120
```

In [215]:
rosetta_2020_df.drop(37191, inplace=True)

In [216]:
rosetta_2020_df.drop(37193, inplace=True)

In [217]:
rosetta_2020_df.drop(37246, inplace=True)

In [218]:
duplicateRowsDF = rosetta_2020_df[rosetta_2020_df.duplicated(['geoid10'], keep=False)]
 
print("Duplicate Rows based on a single column are:", duplicateRowsDF, sep='\n')

Duplicate Rows based on a single column are:
Empty DataFrame
Columns: [geoid10, precinct_2020]
Index: []

In [219]:
rosetta_2020_df.to_csv('./temp_data/precinct_block_key_2020.csv', index=False)

In [220]:
merge_final = census_df.merge(rosetta_2020_df, on='geoid10', how='left')

In [221]:
merge_final.drop(columns='precinct', inplace=True)  # keeping only precinct_2020

In [222]:
list(merge_final.columns)

['geoid10',
 'SUMLEV',
 'STATE',
 'COUNTY',
 'TRACT',
 'BLOCK',
 'INTPTLAT',
 'INTPTLON',
 'P0010001',
 'P0010002',
 'P0010003',
 'P0010004',
 'P0010005',
 'P0010006',
 'P0010007',
 'P0010008',
 'P0010009',
 'P0010010',
 'P0010011',
 'P0010012',
 'P0010013',
 'P0010014',
 'P0010015',
 'P0010016',
 'P0010017',
 'P0010018',
 'P0010019',
 'P0010020',
 'P0010021',
 'P0010022',
 'P0010023',
 'P0010024',
 'P0010025',
 'P0010026',
 'P0010027',
 'P0010028',
 'P0010029',
 'P0010030',
 'P0010031',
 'P0010032',
 'P0010033',
 'P0010034',
 'P0010035',
 'P0010036',
 'P0010037',
 'P0010038',
 'P0010039',
 'P0010040',
 'P0010041',
 'P0010042',
 'P0010043',
 'P0010044',
 'P0010045',
 'P0010046',
 'P0010047',
 'P0010048',
 'P0010049',
 'P0010050',
 'P0010051',
 'P0010052',
 'P0010053',
 'P0010054',
 'P0010055',
 'P0010056',
 'P0010057',
 'P0010058',
 'P0010059',
 'P0010060',
 'P0010061',
 'P0010062',
 'P0010063',
 'P0010064',
 'P0010065',
 'P0010066',
 'P0010067',
 'P0010068',
 'P0010069',
 'P0010070',
 'P0010071',
 'P0020001',
 'P0020002',
 'P0020003',
 'P0020004',
 'P0020005',
 'P0020006',
 'P0020007',
 'P0020008',
 'P0020009',
 'P0020010',
 'P0020011',
 'P0020012',
 'P0020013',
 'P0020014',
 'P0020015',
 'P0020016',
 'P0020017',
 'P0020018',
 'P0020019',
 'P0020020',
 'P0020021',
 'P0020022',
 'P0020023',
 'P0020024',
 'P0020025',
 'P0020026',
 'P0020027',
 'P0020028',
 'P0020029',
 'P0020030',
 'P0020031',
 'P0020032',
 'P0020033',
 'P0020034',
 'P0020035',
 'P0020036',
 'P0020037',
 'P0020038',
 'P0020039',
 'P0020040',
 'P0020041',
 'P0020042',
 'P0020043',
 'P0020044',
 'P0020045',
 'P0020046',
 'P0020047',
 'P0020048',
 'P0020049',
 'P0020050',
 'P0020051',
 'P0020052',
 'P0020053',
 'P0020054',
 'P0020055',
 'P0020056',
 'P0020057',
 'P0020058',
 'P0020059',
 'P0020060',
 'P0020061',
 'P0020062',
 'P0020063',
 'P0020064',
 'P0020065',
 'P0020066',
 'P0020067',
 'P0020068',
 'P0020069',
 'P0020070',
 'P0020071',
 'P0020072',
 'P0020073',
 'precinct_2020']

In [223]:
merge_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39148 entries, 0 to 39147
Columns: 153 entries, geoid10 to precinct_2020
dtypes: Int64(1), float64(2), int64(150)
memory usage: 46.0 MB

In [224]:
merge_final.to_csv('./temp_data/nyc_2010censusblocks_2020policeprecincts.csv')

Do a pivot table on the precinct to get sums of every population column.

In [225]:
pivot = pd.pivot_table(merge_final, index="precinct_2020", aggfunc=np.sum)

In [226]:
pivot

,BLOCK,COUNTY,INTPTLAT,INTPTLON,P0010001,P0010002,P0010003,P0010004,P0010005,P0010006,...,P0020068,P0020069,P0020070,P0020071,P0020072,P0020073,STATE,SUMLEV,TRACT,geoid10
precinct_2020,,,,,,,,,,,,,,,,,,,,,
1,696693,25193,16814.294503,-30565.843976,66679,64416,50484,2162,89,10569,...,0,0,0,0,0,0,14868,309750,1918885,148931949189546656
5,566081,12139,8102.460483,-14725.579225,52568,51415,13436,2784,81,32795,...,0,0,0,0,0,0,7164,149250,555014,71761395550706000
6,544557,12566,8391.140206,-15244.592289,62226,60490,53227,1316,80,5023,...,0,0,0,0,0,0,7416,154500,1440608,74285674406624464
7,443458,10614,7084.512525,-12873.388050,56355,54055,21520,5992,326,19328,...,0,0,0,0,0,0,6264,130500,207354,62746142073983384
9,341265,8967,5986.744441,-10875.670971,76443,73259,48175,6904,361,10946,...,0,0,0,0,0,0,5292,110250,519179,53009675192131216
10,278217,8967,5990.431084,-10878.095224,50180,48333,35838,4171,170,5653,...,0,0,0,0,0,0,5292,110250,1480900,53009684809278168
13,537401,12017,8025.353224,-14574.777134,93640,90828,70786,4864,194,12883,...,0,0,0,0,1,1,7092,147750,1172000,71040181720537288
14,164443,7259,4849.454468,-8804.380295,20651,20019,12868,1481,56,4964,...,0,0,0,0,0,0,4284,89250,1144500,42912601445164408
17,505367,10187,6805.432780,-12353.157753,79126,77567,63691,1711,71,11097,...,0,0,0,0,0,0,6012,125250,1475682,60221884757325336
18,345569,11102,7418.787342,-13465.041588,54066,52216,37624,3106,168,8462,...,0,0,0,0,0,0,6552,136500,2211125,65631042111595488
19,1091333,20130,13454.960659,-24405.745228,208259,203870,178395,5365,231,16859,...,0,0,0,0,0,0,11880,247500,4405369,119001344054781280
20,453130,8906,5953.850898,-10801.313507,102624,100080,84116,4511,183,9024,...,0,0,0,0,0,0,5256,109500,2329400,52649083294453064
22,53326,3172,2120.616191,-3846.290564,25,25,6,18,0,0,...,0,0,0,0,0,0,1872,39000,743600,18751727436053316
23,386211,8235,5506.812630,-9982.556538,73106,69507,24574,22948,733,5553,...,0,0,0,0,0,0,4860,101250,2285244,48682372852826144
24,511172,9638,6445.740683,-11687.268563,106460,102158,72133,14662,458,7063,...,0,0,0,0,0,0,5688,118500,2917800,56976409178511104
25,295459,9455,6324.534942,-11459.979457,47405,44920,10886,21943,608,1300,...,0,0,0,0,0,0,5580,116250,3213400,55894582134295424
26,219313,6954,4652.632973,-8431.371461,49508,47048,23703,11610,326,6220,...,0,0,0,0,0,0,4104,85500,2391271,41109563912929264
28,219151,6222,4162.053364,-7543.093579,44781,42566,9799,27033,321,1607,...,0,0,0,0,0,0,3672,76500,2201928,36782242019499128
30,258210,6771,4531.663543,-8208.391485,60685,56601,14707,21103,816,1465,...,0,0,0,0,0,0,3996,83250,2547937,40027735479628176
32,250163,7686,5143.275805,-9316.608777,70942,68227,7498,51411,541,1282,...,1,0,0,0,0,0,4536,94500,2887056,45436888870810112
33,417479,10492,7024.792350,-12717.719140,76958,71025,22218,14215,1277,2315,...,0,1,0,0,0,0,6192,129000,4396010,62024963960517416
34,510567,13298,8907.376002,-16116.240343,113062,104866,47323,12314,1462,2911,...,0,0,0,0,0,0,7848,163500,6218200,78613042182510544
40,816710,1935,15794.190164,-28605.693610,91497,86028,21270,31385,1782,646,...,0,0,0,0,0,0,13932,290250,1774929,139339367750106768
41,715643,1415,11551.037026,-20911.050524,52246,48506,12955,15828,1041,455,...,0,0,0,0,0,0,10188,212250,2940983,101894179410545680
42,496928,1340,10942.864557,-19805.018749,79762,75079,13814,38416,1357,448,...,0,0,0,0,4,4,9648,201000,4087333,96493440873826896
43,1512170,2985,24373.208224,-44095.372740,172122,162252,40191,65492,2207,10187,...,0,0,0,1,0,0,21492,447750,4928314,214949899284652192
44,763160,1765,14414.709741,-26093.862556,146441,137552,25956,58890,2114,2504,...,0,0,0,0,0,0,12708,264750,6228488,127097712285643104
45,2063505,4665,38101.972562,-68874.747434,120833,116361,61310,31256,792,5668,...,0,0,0,0,0,0,33588,699750,23078434,335926880786403712
46,591352,1260,10294.734035,-18625.068434,128200,120132,23931,46932,2326,2140,...,0,0,0,0,0,0,9072,189000,6271031,90732662710901328
47,1696900,3730,30501.052515,-55091.511494,152374,147258,21739,105538,1241,2982,...,0,0,0,0,2,2,26856,559500,31072799,268597610729686912
48,728134,1615,13194.125504,-23865.782321,83266,78828,23662,28195,1377,1027,...,0,0,0,0,0,0,11628,242250,11385331,116296263854038208
49,1056434,2870,23451.732861,-42392.941831,114712,109631,50305,28570,997,8838,...,0,0,0,0,0,0,20664,430500,16785270,206668867853756576
50,848689,2839,16805.650878,-30374.807921,101720,96855,54359,15730,757,5184,...,0,0,0,0,0,0,14796,308250,13010797,147988520108818720
52,750001,1567,11893.087841,-21501.471427,139307,130239,37395,35034,2243,9458,...,0,0,0,0,0,0,10476,218250,10840020,104775778400950016
60,789925,19035,16435.132846,-29961.810088,104278,101803,66276,14998,558,12372,...,0,0,0,0,0,0,14580,303750,14931572,145990499316510016
61,1574096,39151,33814.529632,-61599.175393,159645,156825,121073,5940,299,24223,...,0,0,0,0,0,0,29988,624750,46558717,300271975588744384
62,1061101,26931,23268.202597,-42398.284162,181981,178420,100902,1894,537,63153,...,0,0,0,0,1,1,20628,429750,16580200,206549475803061760
63,1048302,28858,24940.328705,-45389.484908,108646,106194,49114,48543,326,5091,...,0,0,0,0,0,0,22104,460500,43311375,221329013114798336
66,995969,25427,21982.046336,-40025.527688,191382,187193,134948,5312,709,34011,...,0,0,0,0,1,1,19476,405750,18130229,195014451303286272
67,964213,25004,21624.898253,-39332.734146,155252,151852,3902,142116,519,1777,...,0,0,0,0,1,1,19152,399000,45690003,191770496900994560
68,943323,26790,23156.166340,-42193.415729,124491,121140,85271,2288,329,25884,...,0,1,0,0,0,0,20520,427500,6745061,205467967451553728
69,552762,19035,16458.804365,-29929.978618,84480,82675,6885,70837,311,2273,...,0,0,0,0,1,1,14580,303750,40001624,145990750016793056
70,868037,21291,18406.055283,-33503.622137,160664,156129,67162,60984,778,15281,...,0,0,0,0,0,0,16308,339750,30521190,163293215212768320
71,420247,9729,8417.281002,-15307.204757,98429,95882,20812,70414,358,1253,...,0,0,0,0,0,0,7452,155250,11090333,74617400903750144
72,809044,19505,16870.469474,-30710.254400,126230,120736,52711,5849,1573,33565,...,0,0,0,0,0,0,14940,311250,8679316,149595136793969216
73,720813,15322,13257.916156,-24095.008895,86468,83795,5148,70679,675,633,...,0,0,0,0,0,0,11736,244500,22757828,117513447579000736
75,1556841,40373,34935.440380,-63463.818033,183328,175374,26869,105452,1814,9134,...,0,0,0,0,1,1,30924,644250,98314496,309644713146517248
76,688293,14250,12285.284934,-22348.518625,43694,41958,29343,7204,210,2060,...,0,0,0,0,0,0,10872,226500,1821000,108862518210688256
77,392245,9306,8053.510626,-14641.262489,90744,87649,15454,65502,388,2368,...,0,0,0,0,0,0,7128,148500,5802818,71373118028572160
78,490801,11562,10005.506860,-18199.191672,66664,63672,49139,6940,221,3957,...,0,0,0,0,0,0,8856,184500,3501231,88675655012800768
79,430259,9635,8341.182870,-15159.661974,90263,87018,20375,54877,600,2443,...,0,0,0,0,0,0,7380,153750,6849512,73896418495550160
81,382223,8319,7201.389443,-13085.403137,62722,60811,4581,50302,408,1096,...,0,0,0,0,0,0,6372,132750,5781102,63803247811402144
83,652592,15745,13633.078428,-24762.670853,112634,106366,34183,28095,1522,4953,...,0,0,0,0,0,0,12060,251250,14100401,120757591004662608
84,581568,13667,11761.117954,-21382.796770,48196,46319,33297,6470,158,4519,...,0,0,0,0,0,0,10404,216750,572741,104176675727991584
88,507889,12502,10824.269364,-19676.360366,51421,48902,18769,23376,238,3393,...,0,0,0,0,0,0,9576,199500,6154035,95885081540857776
90,1149275,23359,20231.969163,-36752.882988,116836,113116,80364,9974,805,5544,...,0,0,0,0,0,0,17892,372750,25309900,179153843100149504
94,856806,19646,17022.422415,-30910.620395,56247,54566,45462,2037,188,3293,...,0,0,0,0,1,1,15048,313500,22166000,150676681660856864
100,1221909,53703,26904.056539,-48962.699197,47913,46726,29895,12694,165,1347,...,0,0,0,0,0,0,23868,497250,62713786,239217657139082176
101,746803,30537,15306.153361,-27807.968976,67065,64391,19193,35263,533,1278,...,0,0,0,0,0,0,13572,282750,37768219,136025747682936800
102,1129851,59211,29747.690942,-53977.859537,144215,133130,53920,14911,1824,31644,...,0,1,0,2,0,0,26316,548250,10535175,263752215352880224
103,1235387,54027,27148.973140,-49216.198153,105803,98584,12006,48235,1509,17704,...,0,0,0,0,0,0,24012,500250,23716262,240660507163855264
104,1790240,84402,42423.496479,-76995.245174,170190,164755,120143,4320,934,13384,...,0,0,0,0,0,0,37512,781500,60608434,375964626086130816
105,4505946,158402,79607.188990,-144229.654735,188582,180965,33672,107918,941,27881,...,0,0,0,0,0,0,70416,1467000,159692780,705745616932308480
106,2303966,76221,38271.336932,-69475.391177,122441,110973,43894,22601,1653,22456,...,0,0,0,0,0,0,33876,705750,42793559,339522637937893568
107,1842416,75411,37914.633288,-68706.927376,151107,144396,65452,20719,643,47326,...,0,0,0,0,0,0,33516,698250,82710992,335914937111763392
108,1563459,71523,35975.158852,-65273.273068,113200,107851,50190,2937,940,36453,...,0,0,0,0,0,0,31788,662250,16292787,318595392929433600
109,3162860,128061,64460.489755,-116702.724330,247354,240457,95236,6596,555,122496,...,0,0,0,0,0,0,56916,1185750,159664712,570442206650286400
110,1142217,56376,28357.647724,-51408.027999,172634,163788,50935,11427,1700,57640,...,0,0,0,0,0,0,25056,522000,29300348,251124053004622272
111,2792880,107325,54003.704102,-97736.441911,116431,114018,61915,2633,101,45921,...,0,0,0,0,0,0,47700,993750,180001011,478075050012903680
112,1022894,42120,21175.755759,-38402.311012,112070,108553,71381,3240,223,29356,...,0,0,0,0,0,0,18720,390000,36468915,187621564690173088
113,2000978,89748,45075.786517,-81743.514494,120132,116234,3036,104953,696,2615,...,0,0,0,0,0,0,39888,831000,44845522,399777928457222080
114,1458540,64244,33591.535549,-60908.514157,202766,195116,116720,23533,1176,29341,...,0,0,0,0,0,0,29664,618000,10228698,297282542288439232
115,997620,41877,21072.116324,-38194.554148,171576,162076,66142,13700,1914,27250,...,0,0,0,0,0,0,18612,387750,17297118,186538942972177696
120,2022649,83725,40014.609123,-72983.933755,113008,108593,58854,28373,686,8922,...,0,0,0,0,0,0,35460,738750,7173873,355437321740754112
121,2206113,98770,47192.072164,-86165.607454,118708,114773,73769,16688,557,13217,...,0,0,0,0,0,0,41832,871500,29074425,419307990746457536
122,3506740,140590,67110.222093,-122585.290930,138982,136452,119790,3397,330,8474,...,0,0,0,0,0,0,59544,1240500,21820621,596846118209717120
123,2700417,103615,49410.677731,-90449.453086,98032,96794,89264,1399,122,4551,...,0,0,0,0,0,0,43884,914250,24021631,439876390219009344

In [227]:
list(pivot.columns)

['BLOCK',
 'COUNTY',
 'INTPTLAT',
 'INTPTLON',
 'P0010001',
 'P0010002',
 'P0010003',
 'P0010004',
 'P0010005',
 'P0010006',
 'P0010007',
 'P0010008',
 'P0010009',
 'P0010010',
 'P0010011',
 'P0010012',
 'P0010013',
 'P0010014',
 'P0010015',
 'P0010016',
 'P0010017',
 'P0010018',
 'P0010019',
 'P0010020',
 'P0010021',
 'P0010022',
 'P0010023',
 'P0010024',
 'P0010025',
 'P0010026',
 'P0010027',
 'P0010028',
 'P0010029',
 'P0010030',
 'P0010031',
 'P0010032',
 'P0010033',
 'P0010034',
 'P0010035',
 'P0010036',
 'P0010037',
 'P0010038',
 'P0010039',
 'P0010040',
 'P0010041',
 'P0010042',
 'P0010043',
 'P0010044',
 'P0010045',
 'P0010046',
 'P0010047',
 'P0010048',
 'P0010049',
 'P0010050',
 'P0010051',
 'P0010052',
 'P0010053',
 'P0010054',
 'P0010055',
 'P0010056',
 'P0010057',
 'P0010058',
 'P0010059',
 'P0010060',
 'P0010061',
 'P0010062',
 'P0010063',
 'P0010064',
 'P0010065',
 'P0010066',
 'P0010067',
 'P0010068',
 'P0010069',
 'P0010070',
 'P0010071',
 'P0020001',
 'P0020002',
 'P0020003',
 'P0020004',
 'P0020005',
 'P0020006',
 'P0020007',
 'P0020008',
 'P0020009',
 'P0020010',
 'P0020011',
 'P0020012',
 'P0020013',
 'P0020014',
 'P0020015',
 'P0020016',
 'P0020017',
 'P0020018',
 'P0020019',
 'P0020020',
 'P0020021',
 'P0020022',
 'P0020023',
 'P0020024',
 'P0020025',
 'P0020026',
 'P0020027',
 'P0020028',
 'P0020029',
 'P0020030',
 'P0020031',
 'P0020032',
 'P0020033',
 'P0020034',
 'P0020035',
 'P0020036',
 'P0020037',
 'P0020038',
 'P0020039',
 'P0020040',
 'P0020041',
 'P0020042',
 'P0020043',
 'P0020044',
 'P0020045',
 'P0020046',
 'P0020047',
 'P0020048',
 'P0020049',
 'P0020050',
 'P0020051',
 'P0020052',
 'P0020053',
 'P0020054',
 'P0020055',
 'P0020056',
 'P0020057',
 'P0020058',
 'P0020059',
 'P0020060',
 'P0020061',
 'P0020062',
 'P0020063',
 'P0020064',
 'P0020065',
 'P0020066',
 'P0020067',
 'P0020068',
 'P0020069',
 'P0020070',
 'P0020071',
 'P0020072',
 'P0020073',
 'STATE',
 'SUMLEV',
 'TRACT',
 'geoid10']

Drop the non-population columns.

In [228]:
new_pivot = pivot.drop(columns=['STATE',
 'SUMLEV',
 'TRACT',
 'geoid10',
 'BLOCK',
 'COUNTY',
 'INTPTLAT',
 'INTPTLON'
])

Flatten the column headers.

In [229]:
flat_pivot = new_pivot.reset_index()

In [230]:
flat_pivot

,precinct_2020,P0010001,P0010002,P0010003,P0010004,P0010005,P0010006,P0010007,P0010008,P0010009,...,P0020064,P0020065,P0020066,P0020067,P0020068,P0020069,P0020070,P0020071,P0020072,P0020073
0,1,66679,64416,50484,2162,89,10569,26,1086,2263,...,0,1,1,0,0,0,0,0,0,0
1,5,52568,51415,13436,2784,81,32795,18,2301,1153,...,0,1,1,0,0,0,0,0,0,0
2,6,62226,60490,53227,1316,80,5023,21,823,1736,...,0,2,2,0,0,0,0,0,0,0
3,7,56355,54055,21520,5992,326,19328,28,6861,2300,...,0,2,0,2,0,0,0,0,0,0
4,9,76443,73259,48175,6904,361,10946,45,6828,3184,...,0,2,1,1,0,0,0,0,0,0
5,10,50180,48333,35838,4171,170,5653,15,2486,1847,...,0,2,1,1,0,0,0,0,0,0
6,13,93640,90828,70786,4864,194,12883,39,2062,2812,...,0,0,0,0,0,0,0,0,1,1
7,14,20651,20019,12868,1481,56,4964,13,637,632,...,0,0,0,0,0,0,0,0,0,0
8,17,79126,77567,63691,1711,71,11097,45,952,1559,...,0,0,0,0,0,0,0,0,0,0
9,18,54066,52216,37624,3106,168,8462,27,2829,1850,...,0,0,0,0,0,0,0,0,0,0
10,19,208259,203870,178395,5365,231,16859,57,2963,4389,...,0,1,1,0,0,0,0,0,0,0
11,20,102624,100080,84116,4511,183,9024,34,2212,2544,...,0,0,0,0,0,0,0,0,0,0
12,22,25,25,6,18,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13,23,73106,69507,24574,22948,733,5553,77,15622,3599,...,0,4,4,0,0,0,0,0,0,0
14,24,106460,102158,72133,14662,458,7063,55,7787,4302,...,0,1,1,0,0,0,0,0,0,0
15,25,47405,44920,10886,21943,608,1300,41,10142,2485,...,0,2,1,1,0,0,0,0,0,0
16,26,49508,47048,23703,11610,326,6220,29,5160,2460,...,0,0,0,0,0,0,0,0,0,0
17,28,44781,42566,9799,27033,321,1607,43,3763,2215,...,0,4,3,1,0,0,0,0,0,0
18,30,60685,56601,14707,21103,816,1465,42,18468,4084,...,0,3,3,0,0,0,0,0,0,0
19,32,70942,68227,7498,51411,541,1282,33,7462,2715,...,0,3,1,1,1,0,0,0,0,0
20,33,76958,71025,22218,14215,1277,2315,62,30938,5933,...,0,5,1,3,0,1,0,0,0,0
21,34,113062,104866,47323,12314,1462,2911,65,40791,8196,...,0,0,0,0,0,0,0,0,0,0
22,40,91497,86028,21270,31385,1782,646,72,30873,5469,...,0,0,0,0,0,0,0,0,0,0
23,41,52246,48506,12955,15828,1041,455,50,18177,3740,...,0,0,0,0,0,0,0,0,0,0
24,42,79762,75079,13814,38416,1357,448,240,20804,4683,...,0,1,1,0,0,0,0,0,4,4
25,43,172122,162252,40191,65492,2207,10187,174,44001,9870,...,0,3,0,2,0,0,0,1,0,0
26,44,146441,137552,25956,58890,2114,2504,110,47978,8889,...,2,2,2,0,0,0,0,0,0,0
27,45,120833,116361,61310,31256,792,5668,68,17267,4472,...,0,1,1,0,0,0,0,0,0,0
28,46,128200,120132,23931,46932,2326,2140,133,44670,8068,...,0,1,1,0,0,0,0,0,0,0
29,47,152374,147258,21739,105538,1241,2982,89,15669,5116,...,0,0,0,0,0,0,0,0,2,2
30,48,83266,78828,23662,28195,1377,1027,98,24469,4438,...,0,0,0,0,0,0,0,0,0,0
31,49,114712,109631,50305,28570,997,8838,75,20846,5081,...,0,0,0,0,0,0,0,0,0,0
32,50,101720,96855,54359,15730,757,5184,42,20783,4865,...,0,4,4,0,0,0,0,0,0,0
33,52,139307,130239,37395,35034,2243,9458,117,45992,9068,...,0,0,0,0,0,0,0,0,0,0
34,60,104278,101803,66276,14998,558,12372,32,7567,2475,...,0,1,1,0,0,0,0,0,0,0
35,61,159645,156825,121073,5940,299,24223,22,5268,2820,...,0,1,0,1,0,0,0,0,0,0
36,62,181981,178420,100902,1894,537,63153,156,11778,3561,...,0,3,3,0,0,0,0,0,1,1
37,63,108646,106194,49114,48543,326,5091,24,3096,2452,...,0,0,0,0,0,0,0,0,0,0
38,66,191382,187193,134948,5312,709,34011,48,12165,4189,...,0,0,0,0,0,0,0,0,1,1
39,67,155252,151852,3902,142116,519,1777,59,3479,3400,...,0,6,6,0,0,0,0,0,1,1
40,68,124491,121140,85271,2288,329,25884,39,7329,3351,...,0,1,0,0,0,1,0,0,0,0
41,69,84480,82675,6885,70837,311,2273,14,2355,1805,...,0,0,0,0,0,0,0,0,1,1
42,70,160664,156129,67162,60984,778,15281,64,11860,4535,...,0,5,5,0,0,0,0,0,0,0
43,71,98429,95882,20812,70414,358,1253,35,3010,2547,...,0,4,4,0,0,0,0,0,0,0
44,72,126230,120736,52711,5849,1573,33565,62,26976,5494,...,0,1,0,1,0,0,0,0,0,0
45,73,86468,83795,5148,70679,675,633,35,6625,2673,...,0,5,5,0,0,0,0,0,0,0
46,75,183328,175374,26869,105452,1814,9134,177,31928,7954,...,0,3,3,0,0,0,0,0,1,1
47,76,43694,41958,29343,7204,210,2060,21,3120,1736,...,0,0,0,0,0,0,0,0,0,0
48,77,90744,87649,15454,65502,388,2368,45,3892,3095,...,0,1,1,0,0,0,0,0,0,0
49,78,66664,63672,49139,6940,221,3957,31,3384,2992,...,0,1,1,0,0,0,0,0,0,0
50,79,90263,87018,20375,54877,600,2443,88,8635,3245,...,0,0,0,0,0,0,0,0,0,0
51,81,62722,60811,4581,50302,408,1096,20,4404,1911,...,0,1,1,0,0,0,0,0,0,0
52,83,112634,106366,34183,28095,1522,4953,135,37478,6268,...,0,0,0,0,0,0,0,0,0,0
53,84,48196,46319,33297,6470,158,4519,21,1854,1877,...,0,0,0,0,0,0,0,0,0,0
54,88,51421,48902,18769,23376,238,3393,11,3115,2519,...,0,2,1,1,0,0,0,0,0,0
55,90,116836,113116,80364,9974,805,5544,68,16361,3720,...,0,0,0,0,0,0,0,0,0,0
56,94,56247,54566,45462,2037,188,3293,36,3550,1681,...,0,0,0,0,0,0,0,0,1,1
57,100,47913,46726,29895,12694,165,1347,17,2608,1187,...,0,3,3,0,0,0,0,0,0,0
58,101,67065,64391,19193,35263,533,1278,66,8058,2674,...,0,2,2,0,0,0,0,0,0,0
59,102,144215,133130,53920,14911,1824,31644,193,30638,11085,...,0,3,0,0,0,1,0,2,0,0
60,103,105803,98584,12006,48235,1509,17704,166,18964,7219,...,0,5,4,1,0,0,0,0,0,0
61,104,170190,164755,120143,4320,934,13384,87,25887,5435,...,0,0,0,0,0,0,0,0,0,0
62,105,188582,180965,33672,107918,941,27881,157,10396,7617,...,0,3,3,0,0,0,0,0,0,0
63,106,122441,110973,43894,22601,1653,22456,182,20187,11468,...,0,3,3,0,0,0,0,0,0,0
64,107,151107,144396,65452,20719,643,47326,130,10126,6711,...,0,1,1,0,0,0,0,0,0,0
65,108,113200,107851,50190,2937,940,36453,57,17274,5349,...,0,1,1,0,0,0,0,0,0,0
66,109,247354,240457,95236,6596,555,122496,106,15468,6897,...,0,4,4,0,0,0,0,0,0,0
67,110,172634,163788,50935,11427,1700,57640,75,42011,8846,...,0,4,2,2,0,0,0,0,0,0
68,111,116431,114018,61915,2633,101,45921,18,3430,2413,...,0,1,1,0,0,0,0,0,0,0
69,112,112070,108553,71381,3240,223,29356,46,4307,3517,...,0,4,3,1,0,0,0,0,0,0
70,113,120132,116234,3036,104953,696,2615,55,4879,3898,...,2,9,8,1,0,0,0,0,0,0
71,114,202766,195116,116720,23533,1176,29341,168,24178,7650,...,0,2,2,0,0,0,0,0,0,0
72,115,171576,162076,66142,13700,1914,27250,85,52985,9500,...,0,5,1,4,0,0,0,0,0,0
73,120,113008,108593,58854,28373,686,8922,59,11699,4415,...,0,4,4,0,0,0,0,0,0,0
74,121,118708,114773,73769,16688,557,13217,78,10464,3935,...,0,0,0,0,0,0,0,0,0,0
75,122,138982,136452,119790,3397,330,8474,43,4418,2530,...,0,1,0,1,0,0,0,0,0,0
76,123,98032,96794,89264,1399,122,4551,33,1425,1238,...,0,0,0,0,0,0,0,0,0,0

In [231]:
flat_pivot.to_csv('./temp_data/nyc_2010pop_2020precincts.csv', index=False)

Done!